# Generated by Django 4.2.6 on 2023-11-08 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commentinteraction',
            name='isDisliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commentinteraction',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='bundleSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='coursePDF',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='duration',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlistinteraction',
            name='isBookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlistinteraction',
            name='isDisliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlistinteraction',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlistinteraction',
            name='watchCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
