# Generated by Django 4.2.7 on 2023-11-09 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 12, 35, 32, 191661, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='commentinteraction',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 12, 35, 32, 192142, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='playlistinteraction',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 12, 35, 32, 190048, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 12, 35, 32, 188335, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 12, 35, 32, 190778, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='videoorder',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 12, 35, 32, 191200, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 12, 35, 32, 189423, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
