# Generated by Django 4.2.7 on 2023-11-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_videoorder_index_and_more'),
        ('api', '0008_remove_commentinteraction_created_at_and_more'),
    ]

    operations = [
    ]
