# Generated by Django 4.2.7 on 2023-11-09 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20231109_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 19, 38, 47, 701794, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 19, 38, 47, 700810, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 9, 19, 38, 47, 700344, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
