# Generated by Django 4.2.7 on 2023-11-13 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_comment_created_at_alter_playlist_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistinteraction',
            name='watchCount',
        ),
        migrations.AddField(
            model_name='playlistinteraction',
            name='lastWatched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlistinteraction',
            name='watched',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
