# Generated by Django 4.2.7 on 2023-11-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_playlistinteraction_watchcount_and_more'),
        ('api', '0012_remove_playlist_bundlesize_playlist_isdraft'),
    ]

    operations = [
    ]
