# Generated by Django 4.2.6 on 2023-12-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_username_user_name_and_more'),
        ('api', '0014_remove_playlist_isdraft_remove_video_dislikes_and_more'),
    ]

    operations = [
    ]
