# Generated by Django 4.2.6 on 2023-12-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cloudinary_public_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
