# Generated by Django 4.2.6 on 2024-07-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistinteraction',
            name='watched',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
